import { render, screen } from "@/tests/app-test-utils";
import {
  AlarmClockIcon,
  ArchiveIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowRightLeftIcon,
  AudioLinesIcon,
  BedDoubleIcon,
  BellIcon,
  BlocksIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  BuildingIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CarIcon,
  ChartBarIcon,
  ChartColumnIcon,
  CheckCheckIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  CircleCheckBigIcon,
  CircleCheckIcon,
  CircleDollarSignIcon,
  CircleEllipsisIcon,
  CircleIcon,
  CircleSlashIcon,
  CircleStarIcon,
  CircleUserRoundIcon,
  CircleXIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClockArrowRightIcon,
  ClockIcon,
  CloudSyncIcon,
  Columns3Icon,
  CompassIcon,
  ConstructionIcon,
  CopyCheckIcon,
  CopyIcon,
  CornerUpRightIcon,
  CreditCardIcon,
  CrownIcon,
  DollarSignIcon,
  DoorClosedIcon,
  DoorOpenIcon,
  DownloadIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  EyeIcon,
  FileInputIcon,
  FileLockIcon,
  FilePenLineIcon,
  FileQuestionMarkIcon,
  FileTextIcon,
  FileUpIcon,
  FlameIcon,
  ForwardIcon,
  GlobeIcon,
  GlobeXIcon,
  GraduationCapIcon,
  HandIcon,
  HashIcon,
  HelpCircleIcon,
  HistoryIcon,
  HomeIcon,
  HousePlusIcon,
  IdCardIcon,
  ImageIcon,
  ImagesIcon,
  ImageUpIcon,
  InboxIcon,
  KeyIcon,
  KeyRoundIcon,
  LayoutGridIcon,
  LinkIcon,
  ListIcon,
  LoaderIcon,
  LocateIcon,
  LockIcon,
  LogOutIcon,
  MailIcon,
  MapIcon,
  MapPinHouseIcon,
  MapPinIcon,
  MapPinnedIcon,
  MaximizeIcon,
  MegaphoneIcon,
  MessageCircleIcon,
  MessageCircleWarningIcon,
  MessageSquareDotIcon,
  MessageSquareIcon,
  MessageSquareMoreIcon,
  MessageSquareTextIcon,
  MicIcon,
  MinusIcon,
  NavigationIcon,
  NewspaperIcon,
  PaperclipIcon,
  PauseIcon,
  PencilIcon,
  PhoneCallIcon,
  PhoneIcon,
  PhoneIncomingIcon,
  PhoneMissedIcon,
  PhoneOutgoingIcon,
  PinIcon,
  PlayIcon,
  ReceiptTextIcon,
  RefreshCcwDotIcon,
  RefreshCwIcon,
  ReplyAllIcon,
  ReplyIcon,
  RocketIcon,
  RotateCcwIcon,
  RulerIcon,
  ScanBarcodeIcon,
  SendIcon,
  SettingsIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldIcon,
  ShieldUserIcon,
  ShoppingBagIcon,
  ShowerHeadIcon,
  SlidersHorizontalIcon,
  SmartphoneIcon,
  SmileIcon,
  SparklesIcon,
  SpeechIcon,
  SquareArrowUpRightIcon,
  SquareIcon,
  SquarePenIcon,
  StarIcon,
  TagIcon,
  TargetIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  ToiletIcon,
  TrashIcon,
  UserCheckIcon,
  UserIcon,
  UserRoundCheckIcon,
  UserRoundIcon,
  UserRoundPenIcon,
  UsersIcon,
  VideoIcon,
  WalletIcon,
  WorkflowIcon,
  ZapIcon,
} from "../index";

/* ------------------------------------------------------------------ */
/* Lucide icon smoke tests                                             */
/* ------------------------------------------------------------------ */

const LUCIDE_ICONS = [
  ["AlarmClockIcon", AlarmClockIcon],
  ["ArchiveIcon", ArchiveIcon],
  ["ArrowLeftIcon", ArrowLeftIcon],
  ["ArrowRightIcon", ArrowRightIcon],
  ["ArrowRightLeftIcon", ArrowRightLeftIcon],
  ["AudioLinesIcon", AudioLinesIcon],
  ["BedDoubleIcon", BedDoubleIcon],
  ["BellIcon", BellIcon],
  ["BlocksIcon", BlocksIcon],
  ["BriefcaseBusinessIcon", BriefcaseBusinessIcon],
  ["Building2Icon", Building2Icon],
  ["BuildingIcon", BuildingIcon],
  ["CalendarDaysIcon", CalendarDaysIcon],
  ["CalendarIcon", CalendarIcon],
  ["CarIcon", CarIcon],
  ["ChartBarIcon", ChartBarIcon],
  ["ChartColumnIcon", ChartColumnIcon],
  ["CheckCheckIcon", CheckCheckIcon],
  ["CheckIcon", CheckIcon],
  ["ChevronDownIcon", ChevronDownIcon],
  ["ChevronLeftIcon", ChevronLeftIcon],
  ["ChevronRightIcon", ChevronRightIcon],
  ["ChevronsUpDownIcon", ChevronsUpDownIcon],
  ["ChevronUpIcon", ChevronUpIcon],
  ["CircleAlertIcon", CircleAlertIcon],
  ["CircleCheckBigIcon", CircleCheckBigIcon],
  ["CircleCheckIcon", CircleCheckIcon],
  ["CircleDollarSignIcon", CircleDollarSignIcon],
  ["CircleEllipsisIcon", CircleEllipsisIcon],
  ["CircleIcon", CircleIcon],
  ["CircleSlashIcon", CircleSlashIcon],
  ["CircleStarIcon", CircleStarIcon],
  ["CircleUserRoundIcon", CircleUserRoundIcon],
  ["CircleXIcon", CircleXIcon],
  ["ClipboardIcon", ClipboardIcon],
  ["ClipboardListIcon", ClipboardListIcon],
  ["ClockArrowRightIcon", ClockArrowRightIcon],
  ["ClockIcon", ClockIcon],
  ["CloudSyncIcon", CloudSyncIcon],
  ["Columns3Icon", Columns3Icon],
  ["CompassIcon", CompassIcon],
  ["ConstructionIcon", ConstructionIcon],
  ["CopyCheckIcon", CopyCheckIcon],
  ["CopyIcon", CopyIcon],
  ["CornerUpRightIcon", CornerUpRightIcon],
  ["CreditCardIcon", CreditCardIcon],
  ["CrownIcon", CrownIcon],
  ["DollarSignIcon", DollarSignIcon],
  ["DoorClosedIcon", DoorClosedIcon],
  ["DoorOpenIcon", DoorOpenIcon],
  ["DownloadIcon", DownloadIcon],
  ["EllipsisIcon", EllipsisIcon],
  ["EllipsisVerticalIcon", EllipsisVerticalIcon],
  ["EyeIcon", EyeIcon],
  ["FileInputIcon", FileInputIcon],
  ["FileLockIcon", FileLockIcon],
  ["FilePenLineIcon", FilePenLineIcon],
  ["FileQuestionMarkIcon", FileQuestionMarkIcon],
  ["FileTextIcon", FileTextIcon],
  ["FileUpIcon", FileUpIcon],
  ["FlameIcon", FlameIcon],
  ["ForwardIcon", ForwardIcon],
  ["GlobeIcon", GlobeIcon],
  ["GlobeXIcon", GlobeXIcon],
  ["GraduationCapIcon", GraduationCapIcon],
  ["HandIcon", HandIcon],
  ["HashIcon", HashIcon],
  ["HelpCircleIcon", HelpCircleIcon],
  ["HistoryIcon", HistoryIcon],
  ["HomeIcon", HomeIcon],
  ["HousePlusIcon", HousePlusIcon],
  ["IdCardIcon", IdCardIcon],
  ["ImageIcon", ImageIcon],
  ["ImagesIcon", ImagesIcon],
  ["ImageUpIcon", ImageUpIcon],
  ["InboxIcon", InboxIcon],
  ["KeyIcon", KeyIcon],
  ["KeyRoundIcon", KeyRoundIcon],
  ["LayoutGridIcon", LayoutGridIcon],
  ["LinkIcon", LinkIcon],
  ["ListIcon", ListIcon],
  ["LoaderIcon", LoaderIcon],
  ["LocateIcon", LocateIcon],
  ["LockIcon", LockIcon],
  ["LogOutIcon", LogOutIcon],
  ["MailIcon", MailIcon],
  ["MapIcon", MapIcon],
  ["MapPinHouseIcon", MapPinHouseIcon],
  ["MapPinIcon", MapPinIcon],
  ["MapPinnedIcon", MapPinnedIcon],
  ["MaximizeIcon", MaximizeIcon],
  ["MegaphoneIcon", MegaphoneIcon],
  ["MessageCircleIcon", MessageCircleIcon],
  ["MessageCircleWarningIcon", MessageCircleWarningIcon],
  ["MessageSquareDotIcon", MessageSquareDotIcon],
  ["MessageSquareIcon", MessageSquareIcon],
  ["MessageSquareMoreIcon", MessageSquareMoreIcon],
  ["MessageSquareTextIcon", MessageSquareTextIcon],
  ["MicIcon", MicIcon],
  ["MinusIcon", MinusIcon],
  ["NavigationIcon", NavigationIcon],
  ["NewspaperIcon", NewspaperIcon],
  ["PaperclipIcon", PaperclipIcon],
  ["PauseIcon", PauseIcon],
  ["PencilIcon", PencilIcon],
  ["PhoneCallIcon", PhoneCallIcon],
  ["PhoneIcon", PhoneIcon],
  ["PhoneIncomingIcon", PhoneIncomingIcon],
  ["PhoneMissedIcon", PhoneMissedIcon],
  ["PhoneOutgoingIcon", PhoneOutgoingIcon],
  ["PinIcon", PinIcon],
  ["PlayIcon", PlayIcon],
  ["ReceiptTextIcon", ReceiptTextIcon],
  ["RefreshCcwDotIcon", RefreshCcwDotIcon],
  ["RefreshCwIcon", RefreshCwIcon],
  ["ReplyAllIcon", ReplyAllIcon],
  ["ReplyIcon", ReplyIcon],
  ["RocketIcon", RocketIcon],
  ["RotateCcwIcon", RotateCcwIcon],
  ["RulerIcon", RulerIcon],
  ["ScanBarcodeIcon", ScanBarcodeIcon],
  ["SendIcon", SendIcon],
  ["SettingsIcon", SettingsIcon],
  ["ShareIcon", ShareIcon],
  ["ShieldCheckIcon", ShieldCheckIcon],
  ["ShieldIcon", ShieldIcon],
  ["ShieldUserIcon", ShieldUserIcon],
  ["ShoppingBagIcon", ShoppingBagIcon],
  ["ShowerHeadIcon", ShowerHeadIcon],
  ["SlidersHorizontalIcon", SlidersHorizontalIcon],
  ["SmartphoneIcon", SmartphoneIcon],
  ["SmileIcon", SmileIcon],
  ["SparklesIcon", SparklesIcon],
  ["SpeechIcon", SpeechIcon],
  ["SquareArrowUpRightIcon", SquareArrowUpRightIcon],
  ["SquareIcon", SquareIcon],
  ["SquarePenIcon", SquarePenIcon],
  ["StarIcon", StarIcon],
  ["TagIcon", TagIcon],
  ["TargetIcon", TargetIcon],
  ["ThumbsDownIcon", ThumbsDownIcon],
  ["ThumbsUpIcon", ThumbsUpIcon],
  ["ToiletIcon", ToiletIcon],
  ["TrashIcon", TrashIcon],
  ["UserCheckIcon", UserCheckIcon],
  ["UserIcon", UserIcon],
  ["UserRoundCheckIcon", UserRoundCheckIcon],
  ["UserRoundIcon", UserRoundIcon],
  ["UserRoundPenIcon", UserRoundPenIcon],
  ["UsersIcon", UsersIcon],
  ["VideoIcon", VideoIcon],
  ["WalletIcon", WalletIcon],
  ["WorkflowIcon", WorkflowIcon],
  ["ZapIcon", ZapIcon],
] as const;

describe("icons.v2 — Lucide icons", () => {
  describe("individual icon smoke tests", () => {
    it.each(LUCIDE_ICONS)(
      "%s renders an <svg> with stroke='currentColor'",
      (_name, Icon) => {
        const { container } = render(<Icon />);
        const svg = container.querySelector("svg");
        expect(svg).not.toBeNull();
        expect(svg).toBeVisible();
        expect(svg).toHaveAttribute("stroke", "currentColor");
      }
    );
  });

  it("renders every listed lucide icon without crashing", () => {
    const { container } = render(
      <div>
        {LUCIDE_ICONS.map(([name, Icon]) => (
          <Icon data-testid={`icon-${name}`} key={name} />
        ))}
      </div>
    );
    const svgs = container.querySelectorAll("svg");
    expect(svgs).toHaveLength(LUCIDE_ICONS.length);
  });

  it("icons accept className prop", () => {
    const { container } = render(<HomeIcon className="text-red-500" />);
    const svg = container.querySelector("svg");
    expect(svg).toHaveClass("text-red-500");
  });

  it("icons forward additional props to svg", () => {
    render(<HomeIcon data-testid="home-svg" />);
    expect(screen.getByTestId("home-svg")).toBeVisible();
  });
});
